### ISSUE TITLE
Никаких мертвых комментариев!

### ISSUE THREAD

**Issue by boris-dev** [PhantomStyle/liga-internship#3]
Они могут быть во время работы, но при пуше в мастер(даже в свой) их нужно удалять!

https://github.com/PhantomStyle/liga-internship/blob/f5b303e8040f8311fa6b14209ad2ea5fbd071271/javacore-song-task/src/main/java/ru/liga/Changer.java#L24

**Comment by PhantomStyle** [comment]
Сделал
