### ISSUE TITLE
Задача решена в очень узком смысле, для любого имени файла не подойдет

### ISSUE THREAD

**Issue by boris-dev** [PhantomStyle/liga-internship#5]
Невнятный интерфейс использования внутри конструктора создается SimpleMidiFile
и также передается в perform.
Так какой же используется?

https://github.com/PhantomStyle/liga-internship/blob/f5b303e8040f8311fa6b14209ad2ea5fbd071271/javacore-song-task/src/main/java/ru/liga/Changer.java#L23

**Comment by PhantomStyle** [comment]
Сделал
