### ISSUE TITLE
Для каждого класса должен быть свой логгер

### ISSUE THREAD

**Issue by boris-dev** [PhantomStyle/liga-internship#8]
Тогда и + "(from TextSaver)" писать не нужно будет

https://github.com/PhantomStyle/liga-internship/blob/f5b303e8040f8311fa6b14209ad2ea5fbd071271/javacore-song-task/src/main/java/ru/liga/TextSaver.java#L26

**Comment by PhantomStyle** [comment]
Сделал, но для тех классов, которые мне показались нуждаются в логгерах
